"""Add UserImage table

Revision ID: 51f0a8ec38b0
Revises: 9d5ee884541a
Create Date: 2025-02-26 21:02:52.067297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51f0a8ec38b0'
down_revision: Union[str, None] = '9d5ee884541a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
