"""Add UserImage table

Revision ID: 9d5ee884541a
Revises: 006_add_llm_fields
Create Date: 2025-02-26 20:55:22.718805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d5ee884541a'
down_revision: Union[str, None] = '006_add_llm_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.tg_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_images_id'), 'user_images', ['id'], unique=False)
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index(op.f('ix_feedbacks_id'), 'feedbacks', ['id'], unique=False)
    op.drop_constraint('fk_feedbacks_user', 'feedbacks', type_='foreignkey')
    op.create_foreign_key(None, 'feedbacks', 'users', ['user_id'], ['tg_id'])
    op.create_index(op.f('ix_logs_id'), 'logs', ['id'], unique=False)
    op.drop_constraint('fk_logs_user', 'logs', type_='foreignkey')
    op.create_foreign_key(None, 'logs', 'users', ['user_id'], ['tg_id'])
    op.create_index(op.f('ix_subtopics_id'), 'subtopics', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subtopics_id'), table_name='subtopics')
    op.drop_constraint(None, 'logs', type_='foreignkey')
    op.create_foreign_key('fk_logs_user', 'logs', 'users', ['user_id'], ['tg_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_logs_id'), table_name='logs')
    op.drop_constraint(None, 'feedbacks', type_='foreignkey')
    op.create_foreign_key('fk_feedbacks_user', 'feedbacks', 'users', ['user_id'], ['tg_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_feedbacks_id'), table_name='feedbacks')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_index(op.f('ix_user_images_id'), table_name='user_images')
    op.drop_table('user_images')
    # ### end Alembic commands ###
